alias ipinfo="curl ipinfo.io"
alias ipv4="curl ipv4.ip.sb"
alias ipv6="curl ipv6.ip.sb"
alias speed="speedtest-cli --simple"
alias ping-jms="for i in {1..5};do ping c20s$i.jamjams.net -c 5 | grep rtt;done"
